### ISSUE TITLE
Indexing Sort | yue0211

### ISSUE THREAD

**Issue by yue0211** [yue0211/yue0211.github.io#2]
https://yue0211.github.io/ 

 Set Hexo Environment Link To Github參考連結 Set Butterfly Environmentversion 5.2.2參考連結參考連結 Use Search in Blognote: 用太新的 Butterfly Theme 會出錯 1npm install hexo-generator-search --save 123456# 修改: _config.bu

**Comment by EMUARU** [comment]
不要再偷肝了 偷跑猴

**Comment by EMUARU** [comment]
不錯耶 高級功能

**Comment by EMUARU** [comment]
<font color=#FF0000>為甚麼沒有紅色</font>

**Comment by yue0211** [comment]
紅色的什麼
